name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master

    - name: Install node modules
      run: |
        npm install
    - name: Run test
      run: |
        npm test
  fake_deploy:
      name: Fake deploy with metrics
      runs-on: ubuntu-latest
      needs: [test]
      steps:
        - name: Quickmetrics
          uses: screendriver/quickmetrics-action@v1
          with:
            name: fake-deploy
            api-key: ${{ secrets.QUICKMETRICS_API_KEY }}
          
