name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master

    - name: Install node modules
      run: |
        npm install
    - name: Run test
      run: |
        npm test
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  fake_deploy:
      name: Fake deploy with metrics
      runs-on: ubuntu-latest
      steps:
        - name: Quickmetrics
          uses: screendriver/quickmetrics-action@v1
          with:
            name: fake-deploy-mobile
            api-key: ${{ secrets.QUICKMETRICS_API_KEY }}
          
