name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@master

    - name: Create env file
      run: |
        touch .env
        echo API_URL=${{ secrets.API_URL }} >> .env
        cat .env

    - name: Install node modules
      run: |
        npm install
    # - name: Run test
    #   run: |
    #     npm test
  build-android:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          API_URL=${{ secrets.API_URL }} ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
  pull_request:
      name: Fake deploy with metrics
      runs-on: ubuntu-latest
      needs: [build-android, test]
      steps:
        - name: Quickmetrics
          uses: screendriver/quickmetrics-action@v1
          with:
            name: pull-request-mobile
            api-key: ${{ secrets.QUICKMETRICS_API_KEY }}
        - name: Discord notification
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          uses: Ilshidur/action-discord@master
          with:
            args: 'New pull request opened for mobile.'
